INSERT INTO item_info(name, description, img_url) VALUES('Black RAWROW', 'The black and white Delpino pattern on the outside and the super water-repellent processing that does not get wet in the snow and rain.', 'images/bags-backpack1.png');
INSERT INTO item_info(name, description, img_url) VALUES('RAWROW', 'Every design Sarah makes comes out of her hand. Textiles and graphic design are offered in a variety of ways, such as painting, collage, and cutting.', 'images/bags-backpack2.png');
INSERT INTO item_info(name, description, img_url) VALUES('Baseball Pot', 'The \"Baseball Pot Bag\" is a cylindrical bag with a brown coloure canvas fabric embroidered on the baseball.', 'images/bags-backpack3.png');
INSERT INTO item_info(name, description, img_url) VALUES('Arty Party', 'The pattern is the work that Arty the motif of the artist of Misaki-ka and a hair comb by the motifs.', 'images/bags-sholderbag1.png');
INSERT INTO item_info(name, description, img_url) VALUES('Cave Life', 'The \"Cave life\" is an individual in the Hall Gallery in New York, in 2016, to pattern a series of linepaintings.', 'images/bags-sholderbag2.png');
INSERT INTO item_info(name, description, img_url) VALUES('Lucky Pot Bag', 'The chain embroidery technique makes it possible to increase the completeness.', 'images/bags-handbag2.png');
INSERT INTO item_info(name, description, img_url) VALUES('White Univers', 'We introduce the "White Universe 1300 Pack" which entered the universe pattern of Kitty Bunny Pony in the interior.', 'images/bags-backpack3.png');
INSERT INTO item_info(name, description, img_url) VALUES('Twist Pouch', 'The same shape of a rectangular platform to a colorful fabric it is said to have left the party, your pouch series.', 'images/bags-handbag1.png');
INSERT INTO item_info(name, description, img_url) VALUES('Danke Rainbow Square', 'It\'s full of colorful color blocks, but it\'s a bag that suits you in any outfit thanks to its white-colored base.', 'images/bags-sholderbag3.png');
